services:
  db:
    image: 863863988126.dkr.ecr.eu-central-1.amazonaws.com/role-service/db
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: roleservice_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    command: postgres -c 'max_connections=300'

  pgadmin:
    image: 863863988126.dkr.ecr.eu-central-1.amazonaws.com/role-service/pgadmin
    container_name: pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: wit@wit.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: 863863988126.dkr.ecr.eu-central-1.amazonaws.com/role-service/api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/roleservice_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    volumes:
      - ./db/changelog:/liquibase/changelog
    ports:
      - "8090:8000"
    depends_on:
      - db