server:
  port: 8000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/roleservice_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true